- platform: generic
  name: "Office"
  still_image_url: !secret camera_image1
  stream_source: !secret camera_stream1
- platform: generic
  name: "Family Room"
  still_image_url: !secret camera_image2
  stream_source: !secret camera_stream2
- platform: generic
  name: "Front"
  still_image_url: !secret camera_image3
  stream_source: !secret camera_stream3
- platform: generic
  name: "Garage"
  still_image_url: !secret camera_image4
  stream_source: !secret camera_stream4